post_install() {
    gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
    echo '####################################################################'
    echo '# NOTE: If you run client and server on the same machine you will  #'
    echo '#       need to change the default ports                           #'
    echo '####################################################################'
}

post_upgrade() {
    post_install
}

post_remove() {
    post_install
}
